apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlsecure-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlsecure
  template:
    metadata:
      labels:
        app: mlsecure
    spec:
      containers:
      - name: mlsecure
        image: mlsecure:latest
        ports:
        - containerPort: 8443
---
apiVersion: v1
kind: Service
metadata:
  name: mlsecure-service
spec:
  selector:
    app: mlsecure
  ports:
    - protocol: TCP
      port: 443
      targetPort: 8443
